workflows:
  react-native-ios:
    name: React Native iOS
    max_build_duration: 120
    instance_type: mac_mini
    environment:
      vars:
        XCODE_WORKSPACE: 'TestAPp.xcworkspace'
        XCODE_SCHEME: 'TestAPp'
      node: latest
      cocoapods: default
    scripts:
      - name: Install npm dependencies
        script: |
          npm install
          cd ios
          pod install
          xcodebuild clean archive -workspace TestAPp.xcworkspace -scheme TestAPp -archivePath /TestAPp.xcarchive | xcpretty
          xcodebuild -exportArchive -archivePath /TestAPp.xcarchive -exportPath / -exportOptionsPlist /TestAPp.plist | xcpretty
    artifacts:
       - build/ios/ipa/*.ipa
       - /ios/ipa/*.ipa
        