workflows:
  react-native-ios:
    name: React Native iOS
    max_build_duration: 120
    instance_type: mac_mini
    environment:
      vars:
        XCODE_WORKSPACE: 'TestAPp.xcworkspace'
        XCODE_SCHEME: 'TestAPp'
      node: latest
      cocoapods: default
    scripts:
      - name: Install npm dependencies
        script: |
          npm install
          export NODE_BINARY=node
          ../node_modules/react-native/scripts/react-native-xcode.sh
          react-native bundle --entry-file index.js --platform ios --dev false --bundle-output ios/main.jsbundle --assets-dest ios
          cd ios
          pod install
          xcodebuild build -workspace "$XCODE_WORKSPACE" -scheme "$XCODE_SCHEME" -sdk iphonesimulator -configuration Debug CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
    artifacts:
       - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
        