workflows:
  react-native-ios:
    name: React Native iOS
    max_build_duration: 120
    instance_type: mac_mini
    environment:
      vars:
        XCODE_WORKSPACE: 'TestAPp'
        XCODE_SCHEME: 'TestAPp'
      node: latest
      react-native: 0.44.0
      cocoapods: default
    scripts:
      - name: Install npm dependencies
        script: |
          npm install
      - name: Install CocoaPods dependencies
        script: |
          cd ios
          pod install
          xcodebuild \ -workspace "$XCODE_WORKSPACE" \ -scheme "$XCODE_SCHEME" \ -sdk iphonesimulator \ -destination 'platform=iOS Simulator,name=iPhone 12 Pro,OS=14.5' \ clean build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
    artifacts:
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
